name: Build

on:
  push:
    branches:
      - 'releases/**'
      - 'test'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: build_env
          auto-update-conda: true
          python-version: "3.9"

      - name: Activate conda
        run: source ~/.profile; conda list

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.13.1

      - name: Install xsimd
        run: conda install xsimd -y

      - name: Build wheels
        env:
          CIBW_ENVIRONMENT: SLSDM_SIMD_ARCH='<=sse3'
          CIBW_BUILD: cp39*
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
