name: Build

on:
  push:
    branches:
      - 'releases/**'
      - 'test'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      # - uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: 3.9
      #     mamba-version: "*"
      #     channels: conda-forge,defaults
      #     channel-priority: true
      #     activate-environment: build_env
      #     environment-file: build_env.yml

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # update once build dependencies are available

      - name: Build wheels
        env:
          CIBW_BUILD: cp39*
        shell: bash -el {0}
        run: |
          which python
          python -m pip install cibuildwheel==2.13.1
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
