name: Build

on:
  push:
    branches:
      - 'releases/**'
      - 'test'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-name: build_env
          init-shell: bash powershell
          create-args: python=3.9 xsimd=10.0.0
          post-cleanup: 'none'

      - name: Build wheels
        env:
          CONDA_HOME: /usr/local/minimamba
        run: bash build_wheels.sh

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
